[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--production=false"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "public, max-age=0, must-revalidate"

# API Proxy - Forward all /api/* requests to Encore backend
[[redirects]]
  from = "/api/*"
  to = "https://staging-war-roombackend-45-x83i.encr.app/api/:splat"
  status = 200
  force = true
  
# Additional API endpoints if needed
[[redirects]]
  from = "/auth/*"
  to = "https://staging-war-roombackend-45-x83i.encr.app/auth/:splat"
  status = 200
  force = true

# Environment-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    REACT_APP_ENV = "production"
    VITE_ENCORE_API_URL = "https://staging-war-roombackend-45-x83i.encr.app"
    VITE_USE_MOCK_DATA = "false"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_ENCORE_API_URL = "https://staging-war-roombackend-45-x83i.encr.app"
    VITE_USE_MOCK_DATA = "true"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_ENCORE_API_URL = "https://staging-war-roombackend-45-x83i.encr.app"
    VITE_USE_MOCK_DATA = "true"