/**
 * Database Types for Supabase
 * Auto-generated types for type-safe database access
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          org_type:
            | 'political_campaign'
            | 'nonprofit'
            | 'advocacy_group'
            | 'pac'
            | 'union'
            | 'other'
            | null;
          email: string;
          phone: string | null;
          website: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          logo_url: string | null;
          primary_color: string | null;
          secondary_color: string | null;
          description: string | null;
          mission_statement: string | null;
          tax_id: string | null;
          fec_id: string | null;
          subscription_tier: 'free' | 'starter' | 'professional' | 'enterprise';
          subscription_expires_at: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          settings: Json;
          features: Json;
          max_users: number;
          max_contacts: number;
          max_monthly_emails: number;
          max_monthly_sms: number;
          is_active: boolean;
          is_verified: boolean;
          verified_at: string | null;
          founded_date: string | null;
          election_date: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          org_type?:
            | 'political_campaign'
            | 'nonprofit'
            | 'advocacy_group'
            | 'pac'
            | 'union'
            | 'other'
            | null;
          email: string;
          phone?: string | null;
          website?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          logo_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          description?: string | null;
          mission_statement?: string | null;
          tax_id?: string | null;
          fec_id?: string | null;
          subscription_tier?: 'free' | 'starter' | 'professional' | 'enterprise';
          subscription_expires_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          settings?: Json;
          features?: Json;
          max_users?: number;
          max_contacts?: number;
          max_monthly_emails?: number;
          max_monthly_sms?: number;
          is_active?: boolean;
          is_verified?: boolean;
          verified_at?: string | null;
          founded_date?: string | null;
          election_date?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          org_type?:
            | 'political_campaign'
            | 'nonprofit'
            | 'advocacy_group'
            | 'pac'
            | 'union'
            | 'other'
            | null;
          email?: string;
          phone?: string | null;
          website?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          logo_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          description?: string | null;
          mission_statement?: string | null;
          tax_id?: string | null;
          fec_id?: string | null;
          subscription_tier?: 'free' | 'starter' | 'professional' | 'enterprise';
          subscription_expires_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          settings?: Json;
          features?: Json;
          max_users?: number;
          max_contacts?: number;
          max_monthly_emails?: number;
          max_monthly_sms?: number;
          is_active?: boolean;
          is_verified?: boolean;
          verified_at?: string | null;
          founded_date?: string | null;
          election_date?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          org_id: string;
          role: string;
          permissions: string[];
          is_active: boolean;
          is_verified: boolean;
          email_verified_at: string | null;
          last_login_at: string | null;
          last_login_ip: string | null;
          two_factor_enabled: boolean;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          org_id: string;
          role?: string;
          permissions?: string[];
          is_active?: boolean;
          is_verified?: boolean;
          email_verified_at?: string | null;
          last_login_at?: string | null;
          last_login_ip?: string | null;
          two_factor_enabled?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          org_id?: string;
          role?: string;
          permissions?: string[];
          is_active?: boolean;
          is_verified?: boolean;
          email_verified_at?: string | null;
          last_login_at?: string | null;
          last_login_ip?: string | null;
          two_factor_enabled?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      contacts: {
        Row: {
          id: string;
          org_id: string;
          external_id: string | null;
          email: string | null;
          phone: string | null;
          first_name: string;
          last_name: string;
          middle_name: string | null;
          prefix: string | null;
          suffix: string | null;
          date_of_birth: string | null;
          gender: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          county: string | null;
          country: string;
          latitude: number | null;
          longitude: number | null;
          contact_type: 'voter' | 'donor' | 'volunteer' | 'supporter' | 'media' | 'vip' | 'other';
          voter_status: 'registered' | 'unregistered' | 'inactive' | 'purged' | 'unknown' | null;
          voter_id: string | null;
          party_affiliation: string | null;
          precinct: string | null;
          congressional_district: string | null;
          state_legislative_district: string | null;
          tags: string[];
          custom_fields: Json;
          notes: string | null;
          preferred_contact_method: string | null;
          do_not_email: boolean;
          do_not_call: boolean;
          do_not_text: boolean;
          email_bounce_count: number;
          engagement_score: number;
          last_contacted_at: string | null;
          source: string | null;
          acquisition_date: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          external_id?: string | null;
          email?: string | null;
          phone?: string | null;
          first_name: string;
          last_name: string;
          middle_name?: string | null;
          prefix?: string | null;
          suffix?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          county?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          contact_type?: 'voter' | 'donor' | 'volunteer' | 'supporter' | 'media' | 'vip' | 'other';
          voter_status?: 'registered' | 'unregistered' | 'inactive' | 'purged' | 'unknown' | null;
          voter_id?: string | null;
          party_affiliation?: string | null;
          precinct?: string | null;
          congressional_district?: string | null;
          state_legislative_district?: string | null;
          tags?: string[];
          custom_fields?: Json;
          notes?: string | null;
          preferred_contact_method?: string | null;
          do_not_email?: boolean;
          do_not_call?: boolean;
          do_not_text?: boolean;
          email_bounce_count?: number;
          engagement_score?: number;
          last_contacted_at?: string | null;
          source?: string | null;
          acquisition_date?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          external_id?: string | null;
          email?: string | null;
          phone?: string | null;
          first_name?: string;
          last_name?: string;
          middle_name?: string | null;
          prefix?: string | null;
          suffix?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          county?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          contact_type?: 'voter' | 'donor' | 'volunteer' | 'supporter' | 'media' | 'vip' | 'other';
          voter_status?: 'registered' | 'unregistered' | 'inactive' | 'purged' | 'unknown' | null;
          voter_id?: string | null;
          party_affiliation?: string | null;
          precinct?: string | null;
          congressional_district?: string | null;
          state_legislative_district?: string | null;
          tags?: string[];
          custom_fields?: Json;
          notes?: string | null;
          preferred_contact_method?: string | null;
          do_not_email?: boolean;
          do_not_call?: boolean;
          do_not_text?: boolean;
          email_bounce_count?: number;
          engagement_score?: number;
          last_contacted_at?: string | null;
          source?: string | null;
          acquisition_date?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      volunteers: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string | null;
          email: string;
          phone: string | null;
          first_name: string;
          last_name: string;
          date_of_birth: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          skills: string[];
          interests: string[];
          languages: string[];
          availability: Json;
          transportation: boolean;
          background_check_completed: boolean;
          background_check_date: string | null;
          training_completed: string[];
          status: string;
          total_hours: number;
          notes: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id?: string | null;
          email: string;
          phone?: string | null;
          first_name: string;
          last_name: string;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          skills?: string[];
          interests?: string[];
          languages?: string[];
          availability?: Json;
          transportation?: boolean;
          background_check_completed?: boolean;
          background_check_date?: string | null;
          training_completed?: string[];
          status?: string;
          total_hours?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string | null;
          email?: string;
          phone?: string | null;
          first_name?: string;
          last_name?: string;
          date_of_birth?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          skills?: string[];
          interests?: string[];
          languages?: string[];
          availability?: Json;
          transportation?: boolean;
          background_check_completed?: boolean;
          background_check_date?: string | null;
          training_completed?: string[];
          status?: string;
          total_hours?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      events: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          slug: string;
          event_type: string;
          description: string | null;
          start_date: string;
          end_date: string;
          timezone: string;
          is_virtual: boolean;
          virtual_link: string | null;
          venue_name: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          max_attendees: number | null;
          current_attendees: number;
          registration_required: boolean;
          registration_deadline: string | null;
          is_public: boolean;
          status: string;
          tags: string[];
          custom_fields: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          slug: string;
          event_type: string;
          description?: string | null;
          start_date: string;
          end_date: string;
          timezone?: string;
          is_virtual?: boolean;
          virtual_link?: string | null;
          venue_name?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          max_attendees?: number | null;
          current_attendees?: number;
          registration_required?: boolean;
          registration_deadline?: string | null;
          is_public?: boolean;
          status?: string;
          tags?: string[];
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          slug?: string;
          event_type?: string;
          description?: string | null;
          start_date?: string;
          end_date?: string;
          timezone?: string;
          is_virtual?: boolean;
          virtual_link?: string | null;
          venue_name?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          max_attendees?: number | null;
          current_attendees?: number;
          registration_required?: boolean;
          registration_deadline?: string | null;
          is_public?: boolean;
          status?: string;
          tags?: string[];
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      donations: {
        Row: {
          id: string;
          org_id: string;
          contact_id: string | null;
          amount: number;
          currency: string;
          donation_type: 'one_time' | 'recurring' | 'pledge';
          payment_method: 'credit_card' | 'debit_card' | 'ach' | 'check' | 'cash' | 'other' | null;
          status: 'pending' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          transaction_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          donor_first_name: string | null;
          donor_last_name: string | null;
          donor_email: string | null;
          donor_phone: string | null;
          donor_address_line1: string | null;
          donor_address_line2: string | null;
          donor_city: string | null;
          donor_state: string | null;
          donor_postal_code: string | null;
          donor_country: string | null;
          donor_occupation: string | null;
          donor_employer: string | null;
          is_anonymous: boolean;
          campaign: string | null;
          source: string | null;
          dedication: string | null;
          notes: string | null;
          receipt_sent: boolean;
          receipt_sent_at: string | null;
          thank_you_sent: boolean;
          thank_you_sent_at: string | null;
          processing_fee: number | null;
          net_amount: number | null;
          donated_at: string;
          completed_at: string | null;
          failed_at: string | null;
          refunded_at: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          org_id: string;
          contact_id?: string | null;
          amount: number;
          currency?: string;
          donation_type?: 'one_time' | 'recurring' | 'pledge';
          payment_method?: 'credit_card' | 'debit_card' | 'ach' | 'check' | 'cash' | 'other' | null;
          status?: 'pending' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          transaction_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          donor_first_name?: string | null;
          donor_last_name?: string | null;
          donor_email?: string | null;
          donor_phone?: string | null;
          donor_address_line1?: string | null;
          donor_address_line2?: string | null;
          donor_city?: string | null;
          donor_state?: string | null;
          donor_postal_code?: string | null;
          donor_country?: string | null;
          donor_occupation?: string | null;
          donor_employer?: string | null;
          is_anonymous?: boolean;
          campaign?: string | null;
          source?: string | null;
          dedication?: string | null;
          notes?: string | null;
          receipt_sent?: boolean;
          receipt_sent_at?: string | null;
          thank_you_sent?: boolean;
          thank_you_sent_at?: string | null;
          processing_fee?: number | null;
          net_amount?: number | null;
          donated_at?: string;
          completed_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          org_id?: string;
          contact_id?: string | null;
          amount?: number;
          currency?: string;
          donation_type?: 'one_time' | 'recurring' | 'pledge';
          payment_method?: 'credit_card' | 'debit_card' | 'ach' | 'check' | 'cash' | 'other' | null;
          status?: 'pending' | 'completed' | 'failed' | 'refunded' | 'cancelled';
          transaction_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          donor_first_name?: string | null;
          donor_last_name?: string | null;
          donor_email?: string | null;
          donor_phone?: string | null;
          donor_address_line1?: string | null;
          donor_address_line2?: string | null;
          donor_city?: string | null;
          donor_state?: string | null;
          donor_postal_code?: string | null;
          donor_country?: string | null;
          donor_occupation?: string | null;
          donor_employer?: string | null;
          is_anonymous?: boolean;
          campaign?: string | null;
          source?: string | null;
          dedication?: string | null;
          notes?: string | null;
          receipt_sent?: boolean;
          receipt_sent_at?: string | null;
          thank_you_sent?: boolean;
          thank_you_sent_at?: string | null;
          processing_fee?: number | null;
          net_amount?: number | null;
          donated_at?: string;
          completed_at?: string | null;
          failed_at?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      event_registrations: {
        Row: {
          id: string;
          event_id: string;
          volunteer_id: string | null;
          contact_id: string | null;
          registration_date: string;
          registration_source: string | null;
          guest_name: string | null;
          guest_email: string | null;
          guest_phone: string | null;
          number_of_guests: number;
          status: string;
          checked_in: boolean;
          checked_in_at: string | null;
          checked_in_by: string | null;
          payment_required: boolean;
          payment_status: string | null;
          payment_amount: number | null;
          payment_transaction_id: string | null;
          dietary_restrictions: string | null;
          accessibility_needs: string | null;
          special_requests: string | null;
          confirmation_sent: boolean;
          confirmation_sent_at: string | null;
          reminder_sent: boolean;
          reminder_sent_at: string | null;
          volunteer_role: string | null;
          volunteer_shift_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          volunteer_id?: string | null;
          contact_id?: string | null;
          registration_date?: string;
          registration_source?: string | null;
          guest_name?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          number_of_guests?: number;
          status?: string;
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_in_by?: string | null;
          payment_required?: boolean;
          payment_status?: string | null;
          payment_amount?: number | null;
          payment_transaction_id?: string | null;
          dietary_restrictions?: string | null;
          accessibility_needs?: string | null;
          special_requests?: string | null;
          confirmation_sent?: boolean;
          confirmation_sent_at?: string | null;
          reminder_sent?: boolean;
          reminder_sent_at?: string | null;
          volunteer_role?: string | null;
          volunteer_shift_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          volunteer_id?: string | null;
          contact_id?: string | null;
          registration_date?: string;
          registration_source?: string | null;
          guest_name?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          number_of_guests?: number;
          status?: string;
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_in_by?: string | null;
          payment_required?: boolean;
          payment_status?: string | null;
          payment_amount?: number | null;
          payment_transaction_id?: string | null;
          dietary_restrictions?: string | null;
          accessibility_needs?: string | null;
          special_requests?: string | null;
          confirmation_sent?: boolean;
          confirmation_sent_at?: string | null;
          reminder_sent?: boolean;
          reminder_sent_at?: string | null;
          volunteer_role?: string | null;
          volunteer_shift_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      volunteer_shifts: {
        Row: {
          id: string;
          event_id: string;
          volunteer_id: string | null;
          role: string;
          description: string | null;
          start_time: string;
          end_time: string;
          volunteers_needed: number;
          volunteers_assigned: number;
          skills_required: string[];
          status: string;
          checked_in: boolean;
          checked_in_at: string | null;
          checked_out: boolean;
          checked_out_at: string | null;
          scheduled_hours: number | null;
          actual_hours: number | null;
          notes: string | null;
          volunteer_feedback: string | null;
          coordinator_notes: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          volunteer_id?: string | null;
          role: string;
          description?: string | null;
          start_time: string;
          end_time: string;
          volunteers_needed?: number;
          volunteers_assigned?: number;
          skills_required?: string[];
          status?: string;
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_out?: boolean;
          checked_out_at?: string | null;
          scheduled_hours?: number | null;
          actual_hours?: number | null;
          notes?: string | null;
          volunteer_feedback?: string | null;
          coordinator_notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          volunteer_id?: string | null;
          role?: string;
          description?: string | null;
          start_time?: string;
          end_time?: string;
          volunteers_needed?: number;
          volunteers_assigned?: number;
          skills_required?: string[];
          status?: string;
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_out?: boolean;
          checked_out_at?: string | null;
          scheduled_hours?: number | null;
          actual_hours?: number | null;
          notes?: string | null;
          volunteer_feedback?: string | null;
          coordinator_notes?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          enabled: boolean;
          rollout_percentage: number;
          conditions: Json;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string | null;
          enabled?: boolean;
          rollout_percentage?: number;
          conditions?: Json;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          enabled?: boolean;
          rollout_percentage?: number;
          conditions?: Json;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          org_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          details: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          org_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          details?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          org_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          details?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_analytics_dashboard: {
        Args: {
          p_org_id: string;
          p_start_date: string;
          p_end_date: string;
        };
        Returns: Json;
      };
      get_user_permissions: {
        Args: {
          p_user_id: string;
        };
        Returns: string[];
      };
      check_feature_flag: {
        Args: {
          p_flag_key: string;
          p_user_id?: string;
          p_org_id?: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      organization_type:
        | 'political_campaign'
        | 'nonprofit'
        | 'advocacy_group'
        | 'pac'
        | 'union'
        | 'other';
      subscription_tier: 'free' | 'starter' | 'professional' | 'enterprise';
      contact_type: 'voter' | 'donor' | 'volunteer' | 'supporter' | 'media' | 'vip' | 'other';
      voter_status: 'registered' | 'unregistered' | 'inactive' | 'purged' | 'unknown';
      donation_type: 'one_time' | 'recurring' | 'pledge';
      payment_method: 'credit_card' | 'debit_card' | 'ach' | 'check' | 'cash' | 'other';
      donation_status: 'pending' | 'completed' | 'failed' | 'refunded' | 'cancelled';
    };
  };
}
